
name: build switch build and upload demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-nx:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get latest CMake and ninja
        # Using 'latest' branch, the most recent CMake and ninja are installed.
        uses: lukka/get-cmake@latest

      - name: Build
        run: |
            cmake --preset switch
            cmake --build --preset switch -j2

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: borealis-demo
          path: build/switch/demo/borealis_demo.nro
